- name: Install Base Software
  hosts: all
  tasks:      
    - name: install system updates for centos systems
      yum: name=* state=latest update_cache=yes
      become: yes

    - name: install epel-release
      package:
        name: epel-release
        state: present
      become: yes
      
    - name: install base software packages
      package:
        name: ['vim','htop']
        state: present
      become: yes
