- name: Install Base Software
  hosts: all
  remote_user: root
  become: yes
  become_method: su
  tasks:      
    - name: install system updates for centos systems
      yum: name=* state=latest update_cache=yes

    - name: install epel-release
      action: >
        {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
      with_items:
        - epel-release

    - name: install basic packages
      action: >
        {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
      with_items:
        - vim
        - htop
